version: "2"

run:
  timeout: 3m

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - nolintlint
    - bodyclose
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
