version: "2"

run:
  timeout: 3m

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - nolintlint
    - bodyclose

settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
  max-issues-per-linter: 50
  max-same-issues: 5
